# Generated by Django 3.1.7 on 2021-03-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=30)),
                ('descriptions', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descriptions', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('created', models.DateTimeField()),
                ('taskslist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.taskslist')),
            ],
        ),
    ]
